"""rot: high-performance short-form video creation."""

from .captions import AssCaptionRenderer
from .clips import (
    ClipCandidate,
    ClipDetectionSettings,
    ClipSearchResult,
    FolderClipFinder,
    SkippedSource,
    VideoClipFinder,
    YouTubeClipFinder,
    discover_videos,
)
from .effects import BuiltinEffect
from .errors import (
    AlignmentError,
    ClipAnalysisError,
    ConfigurationError,
    DependencyError,
    DownloadError,
    ParserError,
    ProbeError,
    PublishError,
    PublishTimeoutError,
    RenderError,
    RotError,
    ScriptError,
    VoiceError,
)
from .integrations import ChatterboxVoice, KokoroVoice, OpenRouterParser, StableTSAligner
from .models import (
    CaptionRenderer,
    CaptionTheme,
    Clip,
    Effect,
    EffectSpec,
    FilterNode,
    MediaInfo,
    Overlay,
    ProgressEvent,
    RenderResult,
    RenderSettings,
    Script,
    ScriptParser,
    Speaker,
    SynthesizedAudio,
    TextOverlay,
    Utterance,
    VoiceProvider,
    WordAligner,
    WordTiming,
)
from .project import Project
from .publish import (
    InstagramPublisher,
    InstagramReel,
    PublishBatchResult,
    PublishFailure,
    PublishJob,
    PublishPreflight,
    PublishResult,
    StaticTokenProvider,
    TikTokPublisher,
    TikTokVideo,
    TokenProvider,
    YouTubePublisher,
    YouTubeShort,
    publish_all,
)
from .script import RotScriptParser

__all__ = [
    "AlignmentError",
    "AssCaptionRenderer",
    "BuiltinEffect",
    "CaptionRenderer",
    "CaptionTheme",
    "ChatterboxVoice",
    "Clip",
    "ClipAnalysisError",
    "ClipCandidate",
    "ClipDetectionSettings",
    "ClipSearchResult",
    "ConfigurationError",
    "DependencyError",
    "DownloadError",
    "Effect",
    "EffectSpec",
    "FilterNode",
    "FolderClipFinder",
    "InstagramPublisher",
    "InstagramReel",
    "KokoroVoice",
    "MediaInfo",
    "Overlay",
    "OpenRouterParser",
    "ParserError",
    "ProbeError",
    "PublishBatchResult",
    "PublishError",
    "PublishFailure",
    "PublishJob",
    "PublishPreflight",
    "PublishResult",
    "PublishTimeoutError",
    "ProgressEvent",
    "Project",
    "RenderError",
    "RenderResult",
    "RenderSettings",
    "RotError",
    "RotScriptParser",
    "Script",
    "ScriptError",
    "ScriptParser",
    "SkippedSource",
    "Speaker",
    "StableTSAligner",
    "StaticTokenProvider",
    "SynthesizedAudio",
    "TextOverlay",
    "TikTokPublisher",
    "TikTokVideo",
    "TokenProvider",
    "Utterance",
    "VideoClipFinder",
    "VoiceError",
    "VoiceProvider",
    "WordAligner",
    "WordTiming",
    "YouTubeClipFinder",
    "YouTubePublisher",
    "YouTubeShort",
    "discover_videos",
    "publish_all",
]

__version__ = "0.1.0"
